name: Build & Release
permissions:
  contents: write   # create tags, commits, releases

on:
  push:
    branches: [main, beta]  # main = stable, beta = pre-releases
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  # PRs: compile only (no release)
  build:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: '8.x' }
      - name: Restore
        shell: pwsh
        run: dotnet restore ./StartUp.sln
      - name: Build
        shell: pwsh
        run: dotnet build ./StartUp.sln -c Release --no-restore

  # Pushes to main/beta (or manual dispatch): semantic-release drives everything
  release:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # semantic-release needs tags/history

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install semantic-release + plugins
        run: |
          npm i -D semantic-release \
                 @semantic-release/commit-analyzer \
                 @semantic-release/release-notes-generator \
                 @semantic-release/changelog \
                 @semantic-release/exec \
                 @semantic-release/git \
                 @semantic-release/github

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
