name: Build & Release

on:
  push:
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:            # <-- enables the Run workflow button
    inputs:
      configuration:
        description: Build config
        default: Release
        required: false
      rid:
        description: Runtime (RID)
        default: win-x64
        required: false

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"
      - name: Restore
        run: dotnet restore ./StartUp.sln
      - name: Publish
        run: >
          dotnet publish ./StartUp.csproj
          -c ${{ inputs.configuration || 'Release' }}
          -r ${{ inputs.rid || 'win-x64' }}
          --self-contained true
          -p:PublishSingleFile=true -p:PublishTrimmed=false
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BootWorkspace-publish
          path: **/bin/${{ inputs.configuration || 'Release' }}/net8.0-windows10.0.19041.0/${{ inputs.rid || 'win-x64' }}/publish/**
